plugins:
    effdsnevent:
        is_active: true
        endpoints:
            event:
                backends:
                    NIEP:
                        country_code: "RO"
                        country: "Romania"
                        name: "National Institute for Earth Physics"
                        geometry: [[19.50, 49.00], [30.00, 49.00], [30.00, 42.0], [19.50, 42.0], [19.50, 49.00]]
                        url: "http://eida-sc3.infp.ro/fdsnws/event/1/query"
                    INGV:
                        country_code: "IT"
                        country: "Italy"
                        name: "Istituto Nazionale di Geofisica e Vulcanologia"
                        geometry: [[11.78, 43.95], [13.61, 43.95], [13.61, 42.8], [11.78, 42.8], [11.78, 43.95]]
                        url: "http://webservices.ingv.it/fdsnws/event_taboo/1/query"
                    UNINA:
                        country_code: "IT"
                        country: "Italy"
                        name: "Università degli studi di Napoli"
                        geometry: [[14.0, 41.25], [16.2, 41.25], [16.2, 40.0], [14.0, 40.0], [14.0, 41.25]]
                        url: "http://isnet-bulletin.fisica.unina.it/cgi-bin/fdsnws/event/1/query"
                    RESIF:
                        country_code: "FR"
                        country: "France"
                        name: ""
                        geometry: [[21.35, 38.65], [22.5, 38.65], [22.5, 38.0], [21.35, 38.0], [21.35, 38.65]]
                        url: "http://nfocrl.u-strasbg.fr/fdsnws/event/1/query"
